apiVersion: v1
data:
  amq.host: 'tcp://10.46.42.14:61616'
  amq.valenet-host: 'tcp://10.46.42.14:61616'
  amq.valenet.host: 'tcp://10.46.42.14:61616'
  log.console: 'true'
  log.activate: 'true'
  log.payload: 'true'
  app.global.id: 'eh20160010-01-valenet-qa'
  amq.timetolive: '180000'
  management.health.jms.enabled: 'false'
  endpoints.enabled: 'false'
  endpoints.health.enabled: 'true'   
  logging.config: 'classpath:logback.xml'
  environment: 'VALENET-QA' 
  logger.queue: 'vale.br.amq.fuse.logger'
  host.logger.config: 'https://route-edge-secured-fuse-logger-config-qa.apps.pgjwbjq2.eastus2.aroapp.io/loadconf/v1/broker/'
  amq.host.test: 'tcp://10.46.42.14:61616'
  test.application.name: 'eh20160010-01-valenet'
  activemq.queue.request: 'vale.br.amq.getmasterdata.request'
  activemq.queue.response: 'vale.br.amq.getmasterdata.response'
  azure.soapAction: 'http://www.vale.com/EH/EH20160010_01/GetMasterData/getMasterDataResponse'
  azure.endpoint: 'healthandsafety-webservice-qa.azurewebsites.net/Services/MasterDataService.asmx'

  server.address: '0.0.0.0'
  server.port: '8080'
  management.port: '8081'
  amq.test.application.name: 'eh20160010-01-valenet'
kind: ConfigMap
metadata:
  name: eh20160010-01-valenet
  namespace: eh20160010-01-valenet-qa
  