apiVersion: template.openshift.io/v1
kind: Template
objects:
- apiVersion: secrets-store.csi.x-k8s.io/v1
  kind: SecretProviderClass
  metadata:  
    name: ${name}
    namespace: ${namespace}
  spec:
    parameters:
      keyvaultName: ${keyvault}
      objects: |
        array:
          - |
            objectName: amq-usr-eh20160010-01-valenet
            objectType: secret
            objectVersion: ""
          - |
            objectName: amq-pwd-eh20160010-01-valenet
            objectType: secret
            objectVersion: ""  
          - |
            objectName: tok-pwd-eh20160010-01-valenet
            objectType: secret
            objectVersion: ""  
      tenantId: 7893571b-6c2c-4cef-b4da-7d4b266a0626
      usePodIdentity: 'false'
      useVMManagedIdentity: 'false'
      userAssignedIdentityID: ''
    provider: azure
    secretObjects:
      - data:
          - key: azure.autorizationKey
            objectName: tok-pwd-eh20160010-01-valenet
          - key: azure.autorizationKey-dev
            objectName: tok-pwd-eh20160010-01-valenet
          - key: amq.user
            objectName: amq-usr-eh20160010-01-valenet
          - key: amq.password
            objectName: amq-pwd-eh20160010-01-valenet
          - key: amq.valenet.user
            objectName: amq-usr-eh20160010-01-valenet
          - key: amq.valenet.password
            objectName: amq-pwd-eh20160010-01-valenet
          
        secretName: ${name}
        type: Opaque
parameters:
- description: SecretProvicerClass name.
  displayName: name
  name: name
  required: true
- description: SecretProvicerClass namespace.
  displayName: namespace
  name: namespace
  required: true
- description: SecretProvicerClass KeyVault reference.
  displayName: keyvault
  name: keyvault
  required: true